version: '2'
services:
  discovery-server:
    build: discovery-server
    ports:
      - 8761:8761

  gateway:
    build: gateway

  auth-service:
#    environment:
#      MONGODB_PASSWORD: dev-password
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
#    environment:
#      MONGODB_PASSWORD: dev-password
    ports:
      - 27000:27017

  account-service:
#    env_file: dev.env
    build: account-service
    ports:
      - 7000:7000

  account-mongodb:
#    env_file: dev.env
    ports:
      - 27001:27017

#version: '2.1'
#services:
#  config:
#    build: config
#    ports:
#      - 8888:8888
#
#  discovery-server:
#    build: discovery-server
#
#  gateway:
#    build: gateway
#
#  auth-service:
#    build: auth-service
#    ports:
#      - 5000:5000
#
#  auth-mongodb:
#    build: mongodb
#    ports:
#      - 25000:27017
#
#  account-service:
#    build: account-service
#    ports:
#      - 6000:6000
#
#  account-mongodb:
#    build: mongodb
#    ports:
#      - 26000:27017
#
#  note-service:
#    build: note-service
#    ports:
#      - 8000:8000
#
#  note-mongodb:
#    build: mongodb
#    ports:
#      - 28000:27017
#
#  monitoring:
#    build: monitoring

#
#  https://docs.docker.com/compose/extends/#different-environments