server:
  port: 8761
#spring:
#  application:
#    name: discovery-server
#  cloud:
#    config:
#      uri: http://config:8888
#      fail-fast: true
##      password: ${CONFIG_SERVICE_PASSWORD}
#      password: user
#      username: user
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#
#server:
#  port: 8761