security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: password
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:5000/uaa/user

#spring:
#  data:
#    mongodb:
#      host: account-mongodb
#      username: user
#      password: strong-password-here #${MONGODB_PASSWORD}
#      database: piggymetrics

spring:
  datasource:
    url: jdbc:h2:mem:evernote;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /accounts
  port: 7000